-- MySQL Script generated by MySQL Workbench
-- Fri Nov  3 12:19:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ssafyenjoy
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ssafyenjoy` ;

-- -----------------------------------------------------
-- Schema ssafyenjoy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ssafyenjoy` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ssafyenjoy` ;

-- -----------------------------------------------------
-- Table `ssafyenjoy`.`member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ssafyenjoy`.`member` ;

CREATE TABLE IF NOT EXISTS `ssafyenjoy`.`member` (
  `userId` VARCHAR(45) NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  `userPwd` VARCHAR(45) NOT NULL,
  `emailId` VARCHAR(45) NOT NULL,
  `emailDomain` VARCHAR(45) NOT NULL,
  `joinDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;

-- Jwt 로그인을 위해 이거 실행해야 해!!!
alter table member add column token varchar(1000) null default null after joinDate;
-- -----------------------------------------
-- Table `ssafyenjoy`.`comment`
-- -----------------------------------------
CREATE TABLE IF NOT EXISTS `ssafyenjoy`.`comment` (
`articleNo` INT NOT NULL,
`commentNo` INT NOT NULL AUTO_INCREMENT,
  `userId` VARCHAR(45) NOT NULL,
  `commentContent` VARCHAR(255) NOT NULL,
  `commentRegisterTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`commentNo`),
  INDEX `articleNo_idx` (`articleNo` ASC) VISIBLE,
  FOREIGN KEY (`articleNo`)
  REFERENCES `board` (`articleNo`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ssafyenjoy`.`board`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ssafyenjoy`.`board`;

CREATE TABLE IF NOT EXISTS `ssafyenjoy`.`board` (
  `articleNo` INT NOT NULL AUTO_INCREMENT,
  `userId` VARCHAR(45) NOT NULL,
  `subject` VARCHAR(45) NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  `hit` INT ZEROFILL NOT NULL,
  `registerTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`articleNo`),
  INDEX `userId_idx` (`userId` ASC) VISIBLE,
  CONSTRAINT `userId`
    FOREIGN KEY (`userId`)
    REFERENCES `ssafyenjoy`.`member` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- 11/16 이거 추가했습니다!
alter table board add column location varchar(45) null default null after content;
alter table board add column startDate varchar(100) null default null after location;
alter table board add column endDate varchar(100) null default null after startDate;
alter table board modify column hit int not null default 0;

-- 11/21 BoardDto에 이미지 추가했습니다.
alter table board add column mainImg varchar(500) null default "https://i.ibb.co/c6GdLvZ/noImg.png" after endDate;
select *
    	from board
    	where userId = "hey"
    	order by articleNo;
        
-- -----------------------------------------
-- Table `ssafyenjoy`.`img` 11/21 추가
-- -----------------------------------------
CREATE TABLE IF NOT EXISTS `ssafyenjoy`.`img` (
  `userId` VARCHAR(45) NOT NULL,
  `profileImg` VARCHAR(500) NOT NULL default "https://i.ibb.co/hZPRfz0/dog.jpg",
  PRIMARY KEY (`userId`),
  INDEX `userId_idx` (`userId` ASC) VISIBLE,
  FOREIGN KEY (`userId`)
  REFERENCES `ssafyenjoy`.`member` (`userId`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;

select * from img;

-- -----------------------------------------
-- Table `ssafyenjoy`.`plan`
-- -----------------------------------------
CREATE TABLE IF NOT EXISTS `ssafyenjoy`.`plan` (
  `planNo` INT NOT NULL AUTO_INCREMENT,
  `userId` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `memo` VARCHAR(255),
  `startDate` VARCHAR(45) NOT NULL,
  `endDate` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`planNo`),
  INDEX `userId_idx` (`userId` ASC) VISIBLE,
  FOREIGN KEY (`userId`)
  REFERENCES `member` (`userId`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------
-- Table `ssafyenjoy`.`plandate` 날짜별 계획
-- -----------------------------------------
CREATE TABLE IF NOT EXISTS `ssafyenjoy`.`plandate` (
  `dateNo` INT NOT NULL AUTO_INCREMENT,
  `planNo` INT NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `dateMemo` VARCHAR(255),
  PRIMARY KEY (`dateNo`),
  INDEX `planNo_idx` (`planNo` ASC) VISIBLE,
  FOREIGN KEY (`planNo`)
  REFERENCES `plan` (`planNo`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------
-- Table `ssafyenjoy`.`plantime` 시간별 계획
-- -----------------------------------------
CREATE TABLE IF NOT EXISTS `ssafyenjoy`.`plantime` (
  `timeNo` INT NOT NULL AUTO_INCREMENT,
  `dateNo` INT NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `timeMemo` VARCHAR(255),
  PRIMARY KEY (`timeNo`),
  INDEX `dateNo_idx` (`dateNo` ASC) VISIBLE,
  FOREIGN KEY (`dateNo`)
  REFERENCES `plandate` (`dateNo`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------
-- Table `ssafyenjoy`.`Sido`
-- -----------------------------------------
DROP TABLE IF EXISTS `ssafyenjoy`.`sido` ;

CREATE TABLE IF NOT EXISTS `ssafyenjoy`.`sido` (
  `sidoCode` INT NOT NULL,
  `sidoName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sidoCode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ssafyenjoy`.`Gugun`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ssafyenjoy`.`gugun` ;

CREATE TABLE IF NOT EXISTS `ssafyenjoy`.`gugun` (
  `gugunCode` INT NOT NULL,
  `gugunName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`gugunCode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ssafyenjoy`.`Marker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ssafyenjoy`.`marker` ;

CREATE TABLE IF NOT EXISTS `ssafyenjoy`.`marker` (
  `markerNo` INT NOT NULL AUTO_INCREMENT,
  `contentTypeId` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `addr1` VARCHAR(45) NOT NULL,
  `addr2` VARCHAR(45) NULL,
  `firstImage` VARCHAR(45) NULL,
  `readCount` INT NOT NULL,
  `latitude` DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  PRIMARY KEY (`markerNo`))
ENGINE = InnoDB;

-- 11/23 추가
-- -----------------------------------------------------
-- Table `ssafyenjoy`.`spring`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafyenjoy`.`spring` (
  `springNo` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `mainImg` VARCHAR(500) NOT NULL,
  `content` VARCHAR(500) NOT NULL,
  `accommodation1` VARCHAR(45) NOT NULL,
  `accommodation2` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`springNo`))
ENGINE = InnoDB;
insert into spring(name, address, mainImg, content, accommodation1, accommodation2)
		values("통영", "경상남도 통영시", "https://i.ibb.co/G5943MC/spring.jpg", "봄이 되면 무언가 새 시작, 새 결심을 하기 마련. 먼 곳으로 떠나 마음을 다잡고 싶다면 통영을 추천한다. 깊은 남해와 그 주위 절경 속을 보면 그동안의 근심걱정은 훌훌 털어버리고 기분 전환을 할 수 있을 테니. 소매물도 또는 서피랑에 올라 풍경을 내려다보거나 통영 루지를 타고 스릴을 즐겨본다면 스트레스가 저절로 풀릴 것이다. 봄에 맛볼 수 있는 이곳의 별미, 도다리쑥국도 꼭 맛보자. 봄을 한입 가득 먹는 맛이다.", "스탠포드 호텔앤리조트 통영", "통영 거북선 호텔");
        
 insert into spring(name, address, mainImg, content, accommodation1, accommodation2)
		values("경주", "경상북도 경주시", "https://i.ibb.co/J7zvycf/spring2.jpg", "대릉원의 가을도 아름답지만, 봄은 또 얼마나 아름다운지! 목련과 벚꽃이 여행객을 반겨줄 것이다. ‘지붕 없는 박물관’이라는 별명에 꼭 맞게 줄지어 있는 문화유산 속, 수학여행을 떠올리며 봄 소풍을 즐겨보자. 교촌마을에서 한옥의 고즈넉한 풍경을 두 눈에 담거나, 황리단길 일대 핫플레이스를 찾아보는 것도 잊지 말자.", "힐튼 경주", "베니키아 스위스 로젠 호텔");       
 
 insert into spring(name, address, mainImg, content, accommodation1, accommodation2)
		values("제주도", "제주특별자치도 제주시, 서귀포시", "https://i.ibb.co/88nfZfD/spring3.jpg", "국내에서 가장 먼저 봄을 맞이하는 제주도 역시 빼놓을 수 없다. 온화한 봄바람이 여행객을 반겨줄 것이다. 초봄에는 아직 떨어지지 않은 동백꽃을, 온연한 봄에는 벚꽃과 유채꽃을, 늦봄에는 수국까지 만날 수 있은 것이 제주도 봄의 매력. 철마다 다양한 꽃과 나무를 볼 수 있는 한림공원이나 독특한 월령리 선인장군락지도 추천한다. 액티비티도 즐기고 싶다면 중문에서 서핑에 도전해보는 것은 어떨까?", "그랜드 조선 제주", "호텔 브릿지 서귀포");

insert into spring(name, address, mainImg, content, accommodation1, accommodation2)
		values("시즈오카", "일본 시즈오카시", "https://i.ibb.co/fD40vLT/spring4.jpg", "일본의 봄은 활기차고 시원해 방문하기 가장 좋은 시기다. 특히 이르면 1월부터 늦어도 5월까지 일본의 각 지방은 활짝 핀 벚꽃으로 화려한 광경이 펼쳐진다. 그 중 시즈오카는 도심에서 벗어나 조용하게 벚꽃을 구경할 수 있는 지역이다. 일본을 대표하는 후지산과 벚꽃을 한 번에 구경할 수 있고, 편안하게 산책하면서 고요한 자연 속에서 봄의 기운을 흠뻑 느낄 수 있다. 하마마츠성 공원에 핀 벚꽃은 성과 어우러져 일본다운 풍경을 자랑하고, 시즈오카 시내에 있는 슨푸성 공원은 수로를 따라 분홍빛으로 물들어 특별한 풍경을 선사한다. 이와모토야마공원은 3월 말 후지산을 배경으로 벚꽃 사진을 찍을 수 있어 인기다.", "닛폰다이라 호텔", "호텔 아소시아 시즈오카");

-- -----------------------------------------------------
-- Table `ssafyenjoy`.`summer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafyenjoy`.`summer` (
  `summerNo` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `mainImg` VARCHAR(500) NOT NULL,
  `content` VARCHAR(500) NOT NULL,
  `accommodation1` VARCHAR(45) NOT NULL,
  `accommodation2` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`summerNo`))
ENGINE = InnoDB;
insert into summer(name, address, mainImg, content, accommodation1, accommodation2)
		values("하와이", "미국 하와이", "https://i.ibb.co/ZM3RgzQ/summer.jpg", "연중 기온이 21도~27도 사이를 오가는 하와이는 언제라도 가기 좋지만, 예산에 민감하다면 성수기의 끝을 알리는 3월부터 알아보는 걸 추천한다. 다이아몬드헤드, 마카푸우 포인트 등 다양한 트래킹 코스를 걷고, 미국에서 가장 긴 집라인을 타고 하와이의 울창한 숲을 가로지르고, 푸릇한 코나 커피 농장을 거니는 등 다양한 액티비티를 즐길 수 있다. 또한, 백사장은 물론, 흑사장, 그리고 그외의 색의 모래로 이루어진 그림 같고 다양한 해변들이 무궁무진하다.", "더 로열 하와이안 어 럭셔리 컬렉션 리조트 와이키키", "애스톤 와이키키 비치 호텔");
        
 insert into summer(name, address, mainImg, content, accommodation1, accommodation2)
		values("발리", "인도네시아 발리", "https://i.ibb.co/QDQfL1B/summer2.jpg", "발리의 건기는 4월부터 시작된다. 습도가 낮고 강수량이 적어 발리의 사누르나 잠바란 섬의 그림 같은 해변에서 일광욕하고 휴식을 취하기 이상적이다. 특히 4월은 비교적 관광객이 몰리지 않는 시기라 쾌적하게 여행을 즐길 수 있다. 잠시 시간을 내어 섬의 고대 사원을 둘러보고 하이킹을 통해 폭포와 동굴과 같은 자연의 경이로움을 느껴볼 수 있다.", "리츠칼튼 발리", "더 카나 쿠타 호텔");       
 
 insert into summer(name, address, mainImg, content, accommodation1, accommodation2)
		values("속초", "강원특별자치도 속초시", "https://i.ibb.co/9HVbbyn/summer3.jpg", "산과 바다, 숲과 계곡 모두를 골라 만날 수 있는 지역이니! 시원한 바다 풍경과 산세를 감상하고 싶다면 속초를 추천한다. 등대전망대 또는 영금정에서 내려다보는 동해 바다와 케이블카를 타고 올라갈 수 있는 설악산이 있기 때문. 물론 등산을 즐기거나 해안로 산책을 하는 것으로 여정을 만들어갈 수도 있다. 속초 닭강정과 오징어순대, 대게 등의 음식 맛보는 것도 잊지 말자. 렌트카로 편안하게 이동하며 동해를 구경해보자.", "라마다 속초 호텔", "씨크루즈호텔 속초");

insert into summer(name, address, mainImg, content, accommodation1, accommodation2)
		values("부산", "부산광역시", "https://i.ibb.co/zRSfbhx/summer4.jpg", "광안리/해운대 해수욕장, 오션뷰 카페, 멋진 야경과 맛집 – 볼거리, 먹거리, 즐길 거리가 참 많은 부산. 남녀노소 모두가 즐거운 국내 여행지 중 한 곳이다. 부산은 한국 제2의 도시답게 고속버스, 기차, 거기에 비행기를 이용해 이동할 수도 있다. 부산 시내에서만 여행을 즐긴다면, 대중교통을 이용해도 충분히 부산 여행을 즐겨볼 수 있다. 하지만, 이동 시간을 단축하고 싶거나, 조금 더 멀리! 구석구석! 여행하고 싶다면, 렌터카를 추천한다.", "시그니엘 부산", "신라스테이 해운대");
-- -----------------------------------------------------
-- Table `ssafyenjoy`.`autumn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafyenjoy`.`autumn` (
  `autumnNo` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `mainImg` VARCHAR(500) NOT NULL,
  `content` VARCHAR(500) NOT NULL,
  `accommodation1` VARCHAR(45) NOT NULL,
  `accommodation2` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`autumnNo`))
ENGINE = InnoDB;
select * from autumn;
delete from autumn where autumnNo='2';
insert into autumn(name, address, mainImg, content, accommodation1, accommodation2)
		values("선바위 공원", "울산광역시 울주군 범서읍", "https://i.ibb.co/S5Dmhy9/autumn.png", "선바위 공원은 봄, 가을 시즌에 소풍을 즐기기 매우 좋은 피크닉 명소로 유명하다. 실제로, 인근 유치원, 울산 근교에서도 피크닉을 즐기기 위해 찾는 울산 현지인 추천 여행지이다. 이번 가을에 가족, 연인과 함께 선바위 공원으로 가을 소풍을 떠나보는 건 어떨까? 가을 햇살, 알록달록 예쁜 낙엽, 선선한 바람, 멋진 선바위 전경이 여러분의 가을 피크닉을 완성시켜 줄 것이다.", "롯데호텔 울산", "스타즈호텔 울산");
        
 insert into autumn(name, address, mainImg, content, accommodation1, accommodation2)
		values("정선", "강원특별자치도 정선군 정선읍", "https://i.ibb.co/XXGSrfM/autumn2.jpg", "자연을 벗 삼아 감성 여행을 즐기고 싶은 여행자들에게 안성맞춤인 강원도 정선. 야외 관광명소도 많고, 경치 좋은 캠핑장도 많아 가을에 캠핑 여행, 단풍 여행을 즐기기에 매우 좋은 여행지이다. 아이를 동반한 가족 여행자라면 정선 양떼목장과 정선 아기동물농장, 삼탄아트마인, 화암동굴, 타임캡슐공원, 상유재, 병방치스카이워크, 레일 바이크 등이 있다. 또, 옛 기차역을 카페로 활용한 나전역 카페, 정선 아리랑시장과 같은 전통시장, 정선 5일장도 구경해보고, 정선 한우, 메밀전병과 막국수 등 정선 맛집도 방문해보자.", "파크로쉬 리조트 앤 웰니스", "하이원 그랜드호텔 메인타워");       
 
 insert into autumn(name, address, mainImg, content, accommodation1, accommodation2)
		values("양산", "경상남도 양산시", "https://i.ibb.co/HX9KRvQ/autumn3.png", "양산은 부산 근교 드라이브 명소 또는 부산 근교 나들이 명소로 많이 찾는다. 양산의 추천 관광명소로는 아름다운 자연경관을 만끽할 수 있는 양산 8경을 추천한다. 내원사 계곡, 홍룡폭포, 오봉산 임경대 등 양산 8경안에는 가볼 만한 곳이 많은데, 특히, 양산 통도사는 양산 팔경 중 제1경으로, 유네스코 세계 유산으로도 등재된 한국 3대 사찰 중 하나이다. 양산은 멋진 자연을 배경으로 하는 뷰가 멋있는 예쁜 카페 또는 음식점도 많으니, 주말 가을 나들이를 계획해보자.", "베니키아호텔양산", "아이엠 호텔");

insert into autumn(name, address, mainImg, content, accommodation1, accommodation2)
		values("수원", "경기도 수원시", "https://i.ibb.co/8jjv9vp/autumn4.jpg", "수원은 주말여행 또는 당일치기 나들이를 떠나도 좋은 여행지이다. 수원에서 가볼 만한 관광지로는 유네스코 세계문화유산에도 등재된 수원화성, 드라마의 촬영지로도 유명한 중국식 정원인 효원공원의 월화원, 피크닉 명소, 야경 명소로 알려진 방화수류정, 한정 기간에만 야간 개장을 하는 화성행궁, 아이와 가볼 만한 수원 화성박물관과 아쿠아플레넷 등이 있다. 수원화성 성곽 둘레길도 많이 찾는 코스 중 하나이니 참고하자. 수원 여행의 점심은 수원 치킨 골목에서 치킨 한 마리 어떨까?", "코트야드 바이 메리어트 수원", "벨라 스위트 호텔");

-- -----------------------------------------------------
-- Table `ssafyenjoy`.`winter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssafyenjoy`.`winter` (
  `winterNo` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `mainImg` VARCHAR(500) NOT NULL,
  `content` VARCHAR(500) NOT NULL,
  `accommodation1` VARCHAR(45) NOT NULL,
  `accommodation2` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`winterNo`))
ENGINE = InnoDB;
select * from winter;

insert into winter(name, address, mainImg, content, accommodation1, accommodation2)
		values("무주", "전라북도 무주군", "https://i.ibb.co/VCW9Pf3/winter.png", "유달리 눈이 펑펑 내린 올겨울, 원래도 겨울 여행지로 사랑받는 무주지만, 유달리 설경이 더욱 근사해졌다. 눈으로 환해진 덕유산에서 눈꽃 트레킹을 즐겨보자. 상고대의 모습은 집에 돌아와서도 머릿속에 한참 남을 것이다. 곤돌라를 타고 정상 근처로 바로 올라가거나, 스키 또는 스노보드를 타는 것은 설산을 즐기는 또 다른 방법! 이렇듯 곤돌라와 스키리조트 등의 시설이 있어 어린 자녀나 부모님과 함께 다녀오기에도 좋다.", "무주 나봄 리조트", "무주 리조텔");
        
 insert into winter(name, address, mainImg, content, accommodation1, accommodation2)
		values("평창", "강원특별자치도 평창", "https://i.ibb.co/0GPQHF7/winter2.jpg", "가장 대표적인 평창 여행 명소는 오대산. 오대산 정상인 비로봉까지 완만한 코스가 있어 등산 초보자라도 큰 무리 없이 다녀올 수 있다. 쭉쭉 뻗은 나무 사이 소복이 쌓인 눈을 보며 마음과 몸을 상쾌하게 만들어보자. 또는 선자령에 오르는 것도 추천한다. 이곳 역시 눈꽃 산행 또는 겨울 산행을 즐기기에 안성맞춤인 풍경이 기다리고 있으니. 양떼목장으로 사랑받는 대관령 역시 평창에 있으니 눈 덮인 풍경을 가득 즐겨보자", "홀리데이인&스위트 알펜시아 평창", "켄싱턴호텔 평창");       
 
 insert into winter(name, address, mainImg, content, accommodation1, accommodation2)
		values("인제", "강원특별자치도 인제", "https://i.ibb.co/rH92jSw/winter3.jpg", "하얀 설경이 보고 싶다면 강원도 인제가 딱. 강원도 겨울여행지로 사랑받는 인제의 원대리 자작나무 숲속 길쭉하게 뻗은 나무 사이로 겨울 왕국을 만날 수 있다. 원대리 자작나무숲만 당일치기로 방문하는 것도 좋다. 그러나 겨울을 더욱 만끽하고 싶다면 필례 게르마늄 온천에 따뜻하게 몸을 담거나, 곰배령을 오르는 눈꽃 트레킹에 도전해보는 것도 추천한다. 곰배령에 가려면 인터넷 예약이 필수이니 방문에 참고하자.", "인제 스피디움 호텔 & 리조트", "인제 스테이");

insert into winter(name, address, mainImg, content, accommodation1, accommodation2)
		values("삿포로", "일본 삿포로", "https://i.ibb.co/MM3hzRT/winter4.jpg", "새하얀 설원에 덩그러니 남아있는 나무 한그루, 영화 러브레터 속 낭만적인 그 곳! 삿포로는 로맨틱한 풍경과 부담 없는 거리 덕분에 한국인 사이에서 겨울철 대표 여행지로 꼽히는 곳인데요. 훗카이도행 항공권은 12월부터 2월까지 극성수기로 항공권 값은 평소보나 1.5배 오르지만 겨울 눈 구경은 당연 삿포로라고 자부할수 있습니다.세계 3대 눈축제인 하나인 삿포로 눈축제는 매년 겨울 삿포로를 방문한다면 꼭 방문해야하는 축제입니다.", "JR 타워 호텔 닛코 삿포로", "카락사 호텔 삿포로");

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

use ssafyenjoy;

select * from board;

insert into board(userId, subject, content, hit) 
values("ssafy", "하이용ㅇㅇ", "바이하이하이하ㅣㅇ", 1);
insert into member
values('ssafy', '김싸피', '1234', 'ssafy', 'naver.com', '2023-11-03');

select * from member;
commit;

insert into board(articleNo, userId, subject, content, hit) 
values('11','ssafy','1111', '111', '11');

select * from board;

insert into sido(sidoCode, sidoName)
values('1', '2');

select * from sido;
